### ISSUE TITLE
Remove signing address from authentication responses

### ISSUE THREAD

**Issue by needmoney90** [matthewjamesr/Authparty#4]
Given a message and signature, the signing address can be derived, according to this post:

http://bitcoin.stackexchange.com/questions/24280/can-you-always-derive-a-public-bitcoin-address-from-a-message-and-a-random-signa

This means that the inclusion of the signing address in the callback response is redundant, and can be removed from the spec eventually: https://github.com/Authpartyio/Spec/blob/master/QR_Authorization.spec.md#sign-callback-data

**Comment by matthewjamesr** [comment]
@jdogresorg Can I get your inputs on this? Thanks.

**Comment by jdogresorg** [comment]
I believe it is undesirable to force a website operator to try and derive a public key on their own, especially when the address can easily be provided at the time of signing in the callback.

**Comment by needmoney90** [comment]
Fair enough. I was imagining we would provide the libraries to do it, but we can leave the addresses in for now.

**Comment by matthewjamesr** [comment]
Given inputs, closing this issue.
